### ISSUE TITLE
Add support for zsh

### ISSUE THREAD

**Issue by pengux** [Morantron/tmux-fingers#1]
Doesn't seem to work in zsh right now. Pressing `prefix + I` just print the script.

**Comment by arecarn** [comment]
It works on zsh 5.2 for me, but the script is displayed for about a second.

**Comment by Morantron** [comment]
It's supposed to be working on `zsh 5.2` at least. Maybe an old bash version?

What does `/usr/bin/env bash --version` return for you?

**Comment by Morantron** [comment]
As for the 1s delay, I'm working on a performance improvement, should be fixed on next release! Thanks for pointing out @arecarn! :ok_hand:

**Comment by pengux** [comment]
```sh
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

and I'm on Mac OS X

**Comment by Morantron** [comment]
That should be the issue, can you try upgrade to bash 4? I've tested it on OSX with bash 4 and tmux 2.x and it's working.

You need to make sure that `/usr/bin/env bash` returns 4.x version and not the native 3.2 one ( that's under `/bin/bash` )

**Comment by Morantron** [comment]
`/usr/bin/env bash` will return the first bash that it finds in your $PATH, you just need to make sure that `/usr/local/bin/bash` comes before `/bin/bash`

That should work :tm: !

**Comment by pengux** [comment]
I just upgraded bash to version 4 and checked that `/usr/bin/env bash` really is the new version but running tmux-fingers still only show:

```sh
cat /var/folders/v9/7f_8xhsx2j76z59gqtbqz6500000gn/T//tmux-fingers.e19TOU6E | /Users/peter/.tmux/plugins/tmux-fingers/scripts/fingers.sh "%4" "%5" /var/folders/v9/7f_8xhsx2j76z59gqtbqz6500000gn/T//tmux-fingers.e19TOU6E
```

**Comment by pengux** [comment]
Ah, it works after displaying the above script for about 1 second, as @arecarn mentioned. But the problem is that there is no coloring of the identifiers, so I missed them.

**Comment by Morantron** [comment]
Cool! The one second delay should be gone in next update.

I'm still wondering why the lack of colors. Does `printf "\033[1;33m%s\033[0m" "testing"` print as yellow to you? Maybe I should use `tput` instead of `printf`

**Comment by pengux** [comment]
No, that line doesn't print in any color for me. I'm using tmux which supports true color though, so maybe that's the problem.

Another problem I encountered is that trying `ifconfig` and then `prefix + F` just show a blank screen, so no IPs are showing to be yanked.

**Comment by Morantron** [comment]
What about `echo $(tput setaf 3)$(tput bold)testing$(tput sgr0)`?

If you can run `tmux capture-pane -p > output.txt` and provide me the input I can take a look. Make sure to do not leak any sensitive information! :point_up: 

Thanks for all the feedback!

**Comment by pengux** [comment]
`echo $(tput setaf 3)$(tput bold)testing$(tput sgr0)` just print a grey text "testing", no colors either. Here is the output.txt file
[output.txt](https://github.com/Morantron/tmux-fingers/files/250106/output.txt)

**Comment by Morantron** [comment]
Oops, sorry, I meant for the `ifconfig` output.

**Comment by pengux** [comment]
Here is a part of the output from ifconfig that contains an IP address:

```sh
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        options=3<RXCSUM,TXCSUM>
        inet6 ::1 prefixlen 128
        inet 127.0.0.1 netmask 0xff000000
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        nd6 options=1<PERFORMNUD>
```

**Comment by rubiin** [comment]
@Morantron not working on zsh 5.9 and tmux 3.5. Tmux thumbs works tho
