### ISSUE TITLE
Repo/binary version mismatch?

### ISSUE THREAD

**Issue by iovis** [Morantron/tmux-fingers#101]
I keep getting the "update binary" popup when I refresh tmux because it seems like the git check `git describe --tags | sed "s/-.*//g"` is `2.0.2` and the binary is `2.0.1`. I tried building from brew and from source and I get the same behavior

**Comment by Morantron** [comment]
Just published 2.0.3 fixing this! I need to sort out the release process, still doing releases manually and forgot to bump a version number 🙈

**Comment by iovis** [comment]
Haha, no worries, been there myself

**Comment by iovis** [comment]
I can confirm it working! 🎉
