### ISSUE TITLE
Prefix key broken after first pick

### ISSUE THREAD

**Issue by IngoMeyer441** [Morantron/tmux-fingers#102]
Thanks @Morantron for the work you put into this plugin. I have upgraded to the latest version 2.0.3 (and used 1.x before). I have rewritten my tmux config to match the new configuration options, but cannot get the plugin to work properly. Every time I pick an item, my tmux prefix key stops working afterward, and I have to restart tmux to get it working again. My prefix key is ` and it is inserted as a character into the shell after tmux-fingers was run. I have installed the pre-built tmux-fingers binary.

I would like to help with debugging this issue, but I don't really know where to look for the problem cause.

**Comment by Morantron** [comment]
Hey @IngoMeyer441 ! Just pushed a fix in [2.0.4](https://github.com/Morantron/tmux-fingers/releases/tag/2.0.4), let me know if it works for you!

The prefix is temporarily disabled in [fingers] mode to avoid clashing with hints (for exampling pressing <kbd>Ctrl</kbd>+<kbd>B</kbd> in fingers mode should trigger `@fingers-ctrl-action`, even if that is your prefix), and then is restored when exiting. There was a problem related to shell escaping when using backquote.

Still need to refactor some stuff around escaping, but I'll probably wait for 2.1.x to push those.

**Comment by IngoMeyer441** [comment]
Thanks for the quick fix @Morantron. Yes, backtick as prefix key works now!
