### ISSUE TITLE
hint "q" not work

### ISSUE THREAD

**Issue by waynerv** [Morantron/tmux-fingers#105]
hint "q" will just quit fingers mode instead of copy match, maybe we should remove "q" from all layouts or disable it's quit function.

**Comment by waynerv** [comment]
I suggest using `Enter` as one of "exit" function key but leave `q` for hints only.
https://github.com/Morantron/tmux-fingers/blob/c9c6d8e79b8ed71a43fefdebb74de8c6c4708912/src/fingers/commands/load_config.cr#L112

**Comment by Morantron** [comment]
Fixed in 2.0.6. There was a problem with a regex that was supposed to omit some characters from hints.

It might be configurable in the future, but I'll keep it like this right now.
