### ISSUE TITLE
README includes incorrect config values

### ISSUE THREAD

**Issue by pigmonkey** [Morantron/tmux-fingers#108]
The `prefix+J` shortcut for the new jump functionality conflicted with another shortcut in my config. I wanted to remap it. I tried doing so as suggested in the README, but this had no effect.

    set -g @fingers-jump-key X

I skimmed through the code and saw the config loader was looking for `jump_key` rather than `jump-key`. I tried rebinding it that way, and it works as expected.

    set -g @fingers-jump_key X

I haven't changed any of the other defaults, but it looks like the config loader wants underscores on all the things (eg, `ctrl_action` instead of `ctrl-action`). The README should be updated to reflect this.

**Comment by Morantron** [comment]
Just tried and it works in my end with dashes. It also works with underscores but is not supposed to 😂 

Did you source your .tmux.conf after modifying it?

**Comment by pigmonkey** [comment]
Yes, I reloaded after both attempts. Before finding that it worked with the underscore, I also launched a new tmux session just to make sure there wasn't some new config caching thing in tmux that might prevent the change from going through.

**Comment by Morantron** [comment]
Can you share steps (with a .tmux.conf file if possible) where a config option with dashes does not work (like `@fingers-jump-key`)?

I cannot reproduce this on my end.

In any case options with underscores should not work, I'll patch that up in a future release.

**Comment by pigmonkey** [comment]
This is my tmux config: https://github.com/pigmonkey/dotfiles/blob/master/tmux.conf

**Comment by Morantron** [comment]
I see. [This line](https://github.com/pigmonkey/dotfiles/blob/master/tmux.conf#L19) should be placed at the end of your `.tmux.conf`, otherwise plugins will try to read options before they are set.
