### ISSUE TITLE
Text copied doesn't match hinted text

### ISSUE THREAD

**Issue by prurph** [Morantron/tmux-fingers#109]
When using tmux-fingers to copy files from a `git status` I observe the following behavior.

Activate fingers, hinted text is filename:

<img width="594" alt="image" src="https://github.com/Morantron/tmux-fingers/assets/6109531/787bf92a-880b-41a8-927f-257352576701">

Press hint to copy text. I expect the copied text to be "dot_config/tmux/tmux.conf", which is the yellow text in the screenshot. Instead the copied text includes the "modified:" at the beginning of the line:

<img width="689" alt="image" src="https://github.com/Morantron/tmux-fingers/assets/6109531/1e54cb0d-2f1e-4620-a922-1aa1c2ade838">

Any thoughts on what might be going on here? I'm using kitty and have default actions for tmux-fingers. This always happens for this particular output from `git status`, but doesn't happen for all text, so it's not simply always copying the entire line or something like that. Thanks!

**Comment by Morantron** [comment]
This is fixed in the latest version `2.1.1`. You can run `~/.tmux/plugins/tmux-fingers/bin/tmux-fingers version` to check your current version.

**Comment by prurph** [comment]
Thanks! I'm not sure how I managed to have an old version since I'm using tpm and installed within the last few days then selected "build from source", but I can confirm reinstalling to get 2.1.1 has fixed the issue. 🎉
