### ISSUE TITLE
Config values for "@fingers-show-copied-notification" do not work

### ISSUE THREAD

**Issue by IngoMeyer441** [Morantron/tmux-fingers#111]
Setting `@fingers-show-copied-notification` to `"0"` or `"1"` breaks the plugin for me (no hints are displayed at all). If `@fingers-show-copied-notification` is not set, I get copy notifications, although the default value is `"0"`.

**Comment by Morantron** [comment]
Weird, it works on my machine ™️ . What version are you running? You can run the following command to display it:

```
~/.tmux/plugins/tmux-fingers/bin/tmux-fingers version
```

**Comment by IngoMeyer441** [comment]
Sorry for my late reply and happy new year :partying_face: 

I have version 2.0.3. I scrolled through your source code and the sections regarding copy notifications also look good to me... I will try to reduce my `tmux.conf` and see if that helps.

**Comment by IngoMeyer441** [comment]
I reduced my `.tmux.conf` to these lines:

```bash
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'Morantron/tmux-fingers'

run '~/.tmux/plugins/tpm/tpm'
```

On a fresh Arch Linux, it works, but on my system (Manjaro Linux) I always see a copy notification. The error must depend on something else in my system.

**Comment by Morantron** [comment]
> Sorry for my late reply and happy new year 🥳
> 
> I have version 2.0.3. I scrolled through your source code and the sections regarding copy notifications also look good to me... I will try to reduce my `tmux.conf` and see if that helps.

Latest version right now is 2.1.1. You should update the plugin, resource .tmux.conf and at some point you should see a dialog to recompile/download binary.

**Comment by IngoMeyer441** [comment]
Sorry for the noise, with version 2.1.1, everything works just fine!

I have some unattended update scripts and one updates all tpm plugins with

```bash
    "${HOME}/.tmux/plugins/tpm/bin/install_plugins" && \
    "${HOME}/.tmux/plugins/tpm/bin/update_plugins" all
```

For some reason, the fingers binary was not updated with these commands.

**Comment by IngoMeyer441** [comment]
Even when deleting the `tmux-fingers` binary in the `bin` directory, the plugin wizard does not pop up on the next tmux startup. Is this intended? If `tmux-fingers` is installed or updated with tpm key bindings, the update and install process just works fine.

**Comment by Morantron** [comment]
It seems in tpm the bindings source the tmux.conf file again, but those scripts don't. You'll need to source tmux.conf again in your unattended update scripts for the popup to show up.

**Comment by IngoMeyer441** [comment]
Thanks for the tip!
