### ISSUE TITLE
Handle PCRE2 exception: match limit exceeded

### ISSUE THREAD

**Issue by Morantron** [Morantron/tmux-fingers#113]
Originally pointed out here https://github.com/Morantron/tmux-fingers/issues/112#issuecomment-1888057385

It seems to be a PCRE2 exception, although I still don't know under which circumstances it's raised.

**Comment by Morantron** [comment]
@NeilHanlon can you share the contents of the pane that triggered the exception? You mentioned it crashed on empty panes right? I think it could be related to characters in the shell prompt.

- You can open a new pane and figure out the pane id by running `echo $TMUX_PANE`
- Clear screen in that pane.
- In another shell or pane run `tmux capture-pane -J -p -t <value-of-tmux-pane> > /tmp/pane-contents`

**Comment by NeilHanlon** [comment]
So, I went to try and reproduce this... and I can't.

I rebooted over the weekend, so, I guess it is possible that has something to do with it.

I've tried now in a few different panes with varied histories, and I can't seem to reproduce it, so, I think it's safe to close this for now. 

Sorry for the noise, and thank you for your work on Fingers :)

**Comment by Morantron** [comment]
No prob! Thank you! Let me know if it happens to you again
