### ISSUE TITLE
Allow override of system_copy_command

### ISSUE THREAD

**Issue by grota** [Morantron/tmux-fingers#115]
I need to use both x11 and wayland  sessions (not at the same time :) but I have to switch from one to the other).

I have wl-clipboard installed (so I also have the wl-copy bin) but that does not work on x11.

In tmux-yank, thanks to this override:
https://github.com/tmux-plugins/tmux-yank/blob/acfd36e4fcba99f8310a7dfb432111c242fe7392/scripts/helpers.sh#L141
I can have `if-shell 'test "$XDG_SESSION_TYPE" = "x11"' 'set -g @override_copy_command "xsel -i --clipboard"'` in my `~/.tmux.conf`, would it be possibile to have an override here as well?

**Comment by Morantron** [comment]
I think [@finger-main-action](https://github.com/Morantron/tmux-fingers?tab=readme-ov-file#fingers-main-action) would be equivalent here. You'd need to put something like this in your .tmux.conf:

```
if-shell 'test "$XDG_SESSION_TYPE" = "x11"' 'set -g @fingers-main-action "xsel -i --clipboard"'
```

**Comment by grota** [comment]
aand you're right, don't know why I didn't think about that. I'm closing this, sorry for the noise

**Comment by Morantron** [comment]
no worries! glad it work for you
