### ISSUE TITLE
Select specific patterns

### ISSUE THREAD

**Issue by musjj** [Morantron/tmux-fingers#117]
It'd be nice if we can select which pattern to use during searching. For example:

```bash
prefix + @fingers-key + u # URLs
prefix + @fingers-key + h # Hashes
prefix + @fingers-key + w # Any space-separated words
```
I sometimes want to select an arbitrary word, but I can't just add it to `@fingers-patterns-*`, since it will add a lot of noise to the default mode. The ability to bind arbitrary patterns would be useful for use-cases like this.

**Comment by Morantron** [comment]
Added in 2.2.0. Check out [this recipe](https://github.com/Morantron/tmux-fingers?tab=readme-ov-file#using-only-specific-patterns)
