### ISSUE TITLE
Fail to match SRI string with some regexp expression

### ISSUE THREAD

**Issue by Avimitin** [Morantron/tmux-fingers#118]
Hi, I found some problem that I can't fix on my own. I am trying to add new regexp pattern for matching the SRI hash string:

```tmux
set -g @fingers-key Space
set -g @fingers-pattern-0 '(sha256|sha384|sha512)-[A-Za-z0-9\+/]+={0,2}( +[!-~]*)?'
run-shell ~/.local/share/tmux/plugins/tmux-fingers/tmux-fingers.tmux
```

But with the above config I found that I still can't copy the whole SRI string:

![image](https://github.com/Morantron/tmux-fingers/assets/30021675/1630bc17-63d3-43a4-8854-4238901ebe08)
<sup>*    grep -P is OK</sup>

![image](https://github.com/Morantron/tmux-fingers/assets/30021675/8e476cd8-d7fa-450a-8eb0-089008352c41)
<sup>*    tmux-fingers can not match the whole string</sup>

Another weird thing is that whatever I add the above config or not, the match is still the same:

![image](https://github.com/Morantron/tmux-fingers/assets/30021675/9f36925e-c302-4782-a56f-3f6d9eba3765)
<sup>*    tmux-fingers matches after config is clear</sup>

I suspect that when tmux-fingers found regexp match for a piece of text by default pattern, it won't match the text using user specified pattern again.

**Comment by Avimitin** [comment]
I think this might related to these implementations:

* https://github.com/Morantron/tmux-fingers/blob/47d986b8a2bfb394c44458ab78b19c5b66d303c2/src/fingers/commands/load_config.cr#L77-L80
* https://github.com/Morantron/tmux-fingers/blob/47d986b8a2bfb394c44458ab78b19c5b66d303c2/src/fingers/hinter.cr#L89

Maybe we should put user defined patterns at the front of the list.

**Comment by Avimitin** [comment]
Verified that after #119 this issue get fixed.

![image](https://github.com/Morantron/tmux-fingers/assets/30021675/222286a2-d36e-4828-a351-1fdf0db0f824)

**Comment by Avimitin** [comment]
Also, SRI hash matching is really useful for web development and nix development, can I add it into default patterns?

**Comment by Morantron** [comment]
> Also, SRI hash matching is really useful for web development and nix development, can I add it into default patterns?

Yep go ahead! You can add some tests in `spec/lib/patterns_spec.cr` and run tests with `crystal spec spec/lib/patterns_spec.cr` in the process.
