### ISSUE TITLE
Path not working (MacOS)

### ISSUE THREAD

**Issue by TimDeve** [Morantron/tmux-fingers#12]
The path yanking is not working properly on MacOS Sierra (tmux 2.3, zsh 5.2), instead of yanking the whole path it only yanks until the next slash.

<pre>
$ echo "/var/www/html/sites/"
<strong>p</strong>var<strong>o</strong>www<strong>i</strong>html<strong>u</strong>sites/
</pre>

**Comment by Morantron** [comment]
can you try to install `gawk`? Try running `brew install gawk`. If that works for you I'll do an update to require `gawk` as a hard dependency.

**Comment by TimDeve** [comment]
It worked. Apologies, I should have read the README more carefully. Thank you for your help.

**Comment by Morantron** [comment]
No worries! It used to work with `awk` as well, but I'll update the docs to state it more clearly. Thanks for reporting! :pray:
