### ISSUE TITLE
fingers-key without prefix?

### ISSUE THREAD

**Issue by perapp** [Morantron/tmux-fingers#121]
Hello!

I Love tmux-fingers!!! But would like to get even quicker access to them!

For some common actions in tmux like switching panes I use non prefixed shortcuts (ex alt-j for jumping to lower pane).
Can I get tmux-fingers to run using alt-f?
After a grep in the tmux-fingers source code I tried adding this to my `.tmux.conf`:
```
bind-key -n M-f run-shell -b "~/.tmux/plugins/tmux-fingers/bin/tmux-fingers send-input fzf"
```

But I get `.tmux/plugins/tmux-fingers/bin/tmux-fingers send-input fzf returned 1`

**Comment by Morantron** [comment]
Hi!

There is an undocumented workaround which is to prepend "-n" to the @fingers-key option. Like this:

```
set -g @fingers-key "-n M-f"
```

This might stop working in a feature release though, as I'm trying to figure out a way to allow more customizable key bindings in general.

**Comment by perapp** [comment]
Perfect! Thank you @Morantron. Works like a charm. No problem with dropping support in the future. I will notice when alt-f stops working :-)
