### ISSUE TITLE
Broken behaviour in case of multiple users

### ISSUE THREAD

**Issue by rudenkornk** [Morantron/tmux-fingers#126]
It looks like the logging file [always evaluates to a global fixed path](https://github.com/Morantron/tmux-fingers/blob/3e1d0a8d85fcdbb7223ebfb3b0e1731083dfc8b7/src/fingers/dirs.cr#L11) like `/tmp/fingers.log` or something similar.

This becomes an issue in case there are at least two users on the same system, which use this plugin.
The first user created this file "wins" the race and is able to use the plugin normally, wheras the second user has a non-working plugin due to lack of access to the global file.

**Comment by Morantron** [comment]
Fixed in 2.2.2, thanks!
