### ISSUE TITLE
tmux server exited unexpectedly after copying with tmux-fingers

### ISSUE THREAD

**Issue by raphaelmaenle** [Morantron/tmux-fingers#129]
After updating from ubuntu22.04 to ubuntu24.04 I am experiencing consistent server crashes when using tmux-fingers.;

### Steps to reproduce
- start new tmux session `tmux -vvv`
- activate tmux-fingers, for me this is `<ctrl> + a; f`
- copy any line, eg with `b`
- wait for 1 second until mesage `server exited unexpectedly` appears

### Log Files
[tmux-client-823597.log](https://github.com/user-attachments/files/16849697/tmux-client-823597.log)
[tmux-out-823599.log](https://github.com/user-attachments/files/16849699/tmux-out-823599.log)
[tmux-server-823599.log](https://github.com/user-attachments/files/16849700/tmux-server-823599.log)

### Minimal Tmux Config:

```
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g @plugin 'Morantron/tmux-fingers'
set -g @fingers-key f

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```

### Tmux Version:
tmux 3.3a

**Comment by Morantron** [comment]
is there any logs in ~/.local/state/tmux-fingers/fingers.log or /tmp/fingers.log ?

**Comment by Morantron** [comment]
Cannot reproduce.
