### ISSUE TITLE
URLs do not open

### ISSUE THREAD

**Issue by pmatulis** [Morantron/tmux-fingers#132]
On Ubuntu 22.04 a hinted URL is only copied, not copied *and* opened in a browser.

**Comment by Morantron** [comment]
If you want the URL to be opened you need to hold CTRL while typing the hint. Does it work that way?

**Comment by pmatulis** [comment]
It does work but only sometimes. I guess I'm experiencing an instability issue.

Another thing I've noticed is that when `tmux-fingers` is activated my entire terminal window can go blank/black.

I will test some more and open others issues as needed. I guess this present issue can be closed.

**Comment by Morantron** [comment]
OK!

If you still have the blank screen problem, share your logs (~/.local/state/tmux-fingers/fingers.log) in a new issue.

**Comment by Morantron** [comment]
You might need to update to the latest version of tmux-fingers

**Comment by pmatulis** [comment]
File `~/.tmux/plugins/tmux-fingers/CHANGELOG.md` shows `2.2.2 - 14 Aug 2024` at the top.

**Comment by Morantron** [comment]
Try `~/.tmux/plugins/tmux-fingers/bin/tmux-fingers version`

**Comment by pmatulis** [comment]
```
~/.tmux/plugins/tmux-fingers/bin/tmux-fingers version
2.2.2
```
