### ISSUE TITLE
doesn't work with xclipboard

### ISSUE THREAD

**Issue by acornejo** [Morantron/tmux-fingers#2]
I have custom bindings in my tmux.conf to copy & paste from the X clipboard.

Namely the following snippet:

```
# For x clipboard
if-shell 'test -n "$DISPLAY" && which xclip >/dev/null' 'bind-key -t vi-copy y copy-pipe "xclip -sel clip -i"'
if-shell 'test -n "$DISPLAY" && which xclip >/dev/null' 'bind-key -t vi-copy Enter copy-pipe "xclip -sel clip -i"'
if-shell 'test -n "$DISPLAY" && which xclip >/dev/null' 'bind-key ] run "xclip -sel clip -o | tmux load-buffer - ; tmux paste-buffer"'
```

This makes it so that every time I copy from tmux the text goes to the X clipboard, and every time I paste the text comes from the X clipboard.

Unfortunately tmux-fingers will only copy to the tmux clipboard. It would be cool if there was an option to override the copy command to allow using tmux-fingers with the X clipboard.

**Comment by Morantron** [comment]
That's interesting! Would specifying a script name/path where to pipe the result work for you? The script would have to receive the result through STDIN though.

Meanwhile, tmux-fingers does play nice with https://github.com/tmux-plugins/tmux-yank, but I think that it only works `tmux clipboard -> system clipboard` direction, not both.

Thanks! :dancers:

**Comment by noctuid** [comment]
That would be nice for doing things other than copying as well (e.g. to open a url in browser).

**Comment by acornejo** [comment]
specifying script would be more than enough.

**Comment by Morantron** [comment]
@acornejo just pushed a new version :tada: 

If you update the plugin and set **@fingers-copy-command** you should be able to run integrate with your own script.

**Comment by Morantron** [comment]
> That would be nice for doing things other than copying as well (e.g. to open a url in browser).

@noctuid I've been thinking about this, created a [new issue](https://github.com/Morantron/tmux-fingers/issues/6) for it.
