### ISSUE TITLE
custom highlight format

### ISSUE THREAD

**Issue by charnley** [Morantron/tmux-fingers#22]
Would love a way to set a variable in tmux to change the default highlight format as

    hint_format = "\033[30;1;43m%s\033[0m"
    highlight_format = "\033[1;33m%s\033[0m"

is not readable with my current terminal colorscheme

**Comment by Morantron** [comment]
Implemented in `0.6.0` \o/ :tada: 

![image](https://cloud.githubusercontent.com/assets/3304507/25627687/b6d1c7de-2f63-11e7-94f9-014452ba2247.png)
