### ISSUE TITLE
On invocation, some output message flashes on screen before hints are shown

### ISSUE THREAD

**Issue by ManiacalAce** [Morantron/tmux-fingers#26]
When I do <prefix>-F to invoke hints, I see some log output flash on the screen before it goes back to my regular screen with hints enabled.

Here's a screenshot:
![screenshot from 2017-03-11 00-09-42](https://cloud.githubusercontent.com/assets/960763/23809038/1438f712-05f2-11e7-9588-c38c0fa8d139.png)

I also notice a new window gets opened in tmux, temporarily while hint-mode is active. Not sure if it has any relation.

I'm on zsh, by the way.

**Comment by Morantron** [comment]
Hi! Is this still happening to you? In theory :tm: this message appears in the background, so you shouldn't see it.

**Comment by ManiacalAce** [comment]
@Morantron Yeah, it's still happening. I'm just living with it for now :)
Let me know if I can provide more information.
