### ISSUE TITLE
Activating fingers opens a new window

### ISSUE THREAD

**Issue by dsifford** [Morantron/tmux-fingers#31]
Hello again,

Just updated to 0.6.0. Now when I activate the plugin, it activates fingers mode in a new tmux tab. Is there some new configuration that needs to be set somewhere to prevent this? I breezed the readme and nothing stuck out immediately.

Thanks 😄

**Comment by dsifford** [comment]
Example:

![gif](https://media.giphy.com/media/l0Iy0Fd2yFdz8N1HW/giphy.gif)

**Comment by Morantron** [comment]
I'm afraid it's been like that forever :see_no_evil: 

I'll take it into account for next release!

**Comment by dsifford** [comment]
@Morantron Oh whoops! Sorry about that. Never noticed it before.

The recent update changed the default formatting of the hints slightly so I thought it may have been a misconfiguration on my end.

I got it under control now. No big deal. I'm satisfied! 😄
