### ISSUE TITLE
Improve hint format defaults

### ISSUE THREAD

**Issue by Morantron** [Morantron/tmux-fingers#35]
Depending on user settings ( $TERM, etc, etc ), default hint format is kind of unreadable

![image](https://cloud.githubusercontent.com/assets/3304507/26440684/c0ea3248-412d-11e7-8529-ca1b5ab2b425.png)

**Comment by IonutBajescu** [comment]
True, is there anyone who doesn't use "@fingers-hint-position: right"?

**Comment by Morantron** [comment]
> True, is there anyone who doesn't use "@fingers-hint-position: right"?

:point_up:

**Comment by Morantron** [comment]
fixed on 0.6.3
