### ISSUE TITLE
Custom key

### ISSUE THREAD

**Issue by psamim** [Morantron/tmux-fingers#38]
Hi,
Can I set custom key without prefix to start fingers mode? 
Thanks

**Comment by Morantron** [comment]
Hi!

Looks like docs are wrong, for example: you can  do `@fingers-key "-n C-f"` and you can start fingers mode with just CTRL+F.

Out of curiosity, what key combination do you want to use? :nerd_face:

**Comment by psamim** [comment]
Thanks!

All my tmux keys start with alt key, so I wanted to set fingers key mode to M-f
