### ISSUE TITLE
Cannot yank into clipboard

### ISSUE THREAD

**Issue by psamim** [Morantron/tmux-fingers#39]
Hi,
I am on Archlinux KDE desktop, with tmux 2.5, tpm and tmux-yank.

Unfortunately nothing is copied into clipboard.
I have also tested adding `set -g @fingers-copy-command 'xclip -selection clipboard'`

Any tips?
Thanks

**Comment by Morantron** [comment]
Hi! True, it's broken right now. You have two options

* Remove `@fingers-copy-command` option and revert back to `0.6.1`
* Keep latest version but do `set -g @fingers-copy-command 'nohup xclip -selection clipboard' instead ( I think this should work :tm: )

I still need to dig into the issue, I still don't know wheter culprit is tmux-fingers@0.6.2 or tmux@2.4

I'll keep the issue open until it's fixed :wrench:

Thanks!

**Comment by psamim** [comment]
The second option seems broken.

**Comment by Morantron** [comment]
Oops, did you resource your `tmux.conf` file after the changes?

**Comment by psamim** [comment]
Yes.

**Comment by jarandaf** [comment]
Same issue here, can't yank into clipboard. I am using `0.6.1` tag but still not working. Environment:

- tmux: `2.5`
- bash: `4.4.12`
- shell: `zsh-5.2`
- gawk: `4.1.4`

**Comment by Morantron** [comment]
@jarandaf which OS?

**Comment by jarandaf** [comment]
Have just edited the description @Morantron, thank you!

**Comment by Morantron** [comment]
Also, could you share your `~/.tmux.conf` file?

I should create a GH issue template :see_no_evil:

**Comment by Morantron** [comment]
fixed on 0.6.3

**Comment by jarandaf** [comment]
Thank you @Morantron I do confirm it works now!

**Comment by Morantron** [comment]
>Thank you @Morantron I do confirm it works now!

yaaay :tada:

![](https://media.giphy.com/media/J93sVmfYBtsRi/giphy.gif)
