### ISSUE TITLE
issue when screen has output from ls with -F switch

### ISSUE THREAD

**Issue by damnskippy** [Morantron/tmux-fingers#4]
Minor issue related to sed syntax possibly.

When the screen has output from ls used with -F switch, the / that is put at the end of the directory names somehow makes sed unhappy.  The actual error appears on the screen for a split second.  Had to do a printscreen and saw this for each of the "hidden" directories (names with . as the first character).

sed: 1: " ../s~ ../~ ../ invalid command code .

or another variant for directories that are not hidden.

sed: 1: " scripts/s! scripts/!ad flag in substitute command: 'r'

Only seems to be an issue with ls output.
Did a "echo foo/" and fingers.sh had no trouble selecting it (and copying it).

But at the moment this is how far I triaged it down to.  I haven't looked to fixing it yet - sorry.

**Comment by Morantron** [comment]
Weird, I cannot reproduce it on my machine.

What OS are you using?

Also, can you provide a file with the contents of the screen ( :point_up: don't leak any sensitive information! ). You can run `tmux capture-pane -p > output.txt` to do that.

Thanks!

**Comment by damnskippy** [comment]
Sorry for the delay.
The following output will do it for me.
FWIW, this is on FreeBSD using tmux 2.1

$ l -F
total 28
drwxr-xr-x  26 user  group  12288 May 20 10:30 ../
drwxr-xr-x   2 user  group   4096 May 20 10:31 testdir/
drwxr-xr-x   2 user  group   4096 May 20 10:31 testdir2/
drwxr-xr-x   2 user  group   4096 May 20 10:31 testdir3/
-rw-r--r--   1 user  group      0 May 20 10:31 testfile
-rw-r--r--   1 user  group      0 May 20 10:31 testfile2
-rw-r--r--   1 user  group      0 May 20 10:31 testfile3
drwxr-xr-x   5 user  group   4096 May 20 10:31 ./

**Comment by chrisjunlee** [comment]
@Morantron: I setup a FreeBSD test VM and reduced it to a couple simpler cases:
@damnskippy: I'm not seeing the error messages. Are my repros similar to what you're seeing?
***
**Repro 1:**
1. In tmux, clear screen with **CTRL+L**
2. Invoke t-mux-fingers
![repro_empty_screen](https://cloud.githubusercontent.com/assets/12912753/15441280/e3edbf2a-1e8e-11e6-843c-d53f85f2eea1.gif)
***
**Repro 2:**
1. In tmux, execute **echo test/ test2/**
2. Invoke t-mux-fingers
![repro_echo_slash](https://cloud.githubusercontent.com/assets/12912753/15441287/ea117d38-1e8e-11e6-898b-6864ae16c620.gif)
***
**Environment:**
- FreeBSD 10.3-release
- Tmux 2.1
- Bash 4.3.42-release

**Comment by Morantron** [comment]
Yay! Thanks for the detective work @chrisjunlee! :clap:

I'm setting a BSD virtual machine now, as this will help to spot issues in different platforms with automated tests in the future.

Thanks for the info @damnskippy. The lack of error message is probably because of an old version of tmux-fingers. With the newest version, the bug manifests itself as a blank screen.

So in the end, looks like this ( https://github.com/Morantron/tmux-fingers/issues/7 ) is the same bug also. Let's track the issue there! :ok_hand:

**Comment by Morantron** [comment]
Fixed on version 0.1.2 :tada:
