### ISSUE TITLE
mention user must checkout submodules

### ISSUE THREAD

**Issue by jacob-keller** [Morantron/tmux-fingers#40]
It seems that the behavior changed recently with the addition of a git submodule, and when I upgraded to tmux 2.5, it was broken until I realized to checkout the submodules. This wasn't documented.

**Comment by Morantron** [comment]
Fixed on 0.6.3 with health-check, as well as documented on https://github.com/Morantron/tmux-fingers/blob/master/docs/health-check.md#submodules-not-initialized-properly
