### ISSUE TITLE
Just want to say thank you :)

### ISSUE THREAD

**Issue by id777** [Morantron/tmux-fingers#42]
Thank you so much for this plugin! It's a best plugin what I ever found for tmux. It's like EasyMotion for vim.
And it works exactly the way as I want. Just perfect! 

I'm actually using tmux already for a one year, heard about many plugins for it, but this one (the best one) found just today.

**Comment by Morantron** [comment]
![](https://media.giphy.com/media/wViS9n0RqN2/giphy.gif)

Thank you! I'm glad that you like it :)
