### ISSUE TITLE
Can fingers work with tmux-open plugin?

### ISSUE THREAD

**Issue by id777** [Morantron/tmux-fingers#43]
Hi!
Currently tmux-fingers can only copy to clipboard choosed url/path in fingers mode. That's awesome.

There is plugin https://github.com/tmux-plugins/tmux-open/. It does one thing - open within xdg-open selected file path or url. 
So, to make work tmux-fingers with tmux-open I suppose we need second mode in tmux-fingers - **selection mode.** in additional to current copy mode.

That means what in selection mode, finges should't copy choosen match, but instead just retun it's selection to normal tmux copy mode. Where I can easy press defauld tmux-open key ("o") and selected url/file will open in browser/editor. Or even automatically call tmux-open after path/url will be choosed. 

 What do you think?

**Comment by Morantron** [comment]
It can now! Please upgrade to latest version

https://github.com/Morantron/tmux-fingers#fingers-copy-command-uppercase
