### ISSUE TITLE
Fingers return only part of output if the current pane not in full-screen mode

### ISSUE THREAD

**Issue by vfreefly** [Morantron/tmux-fingers#44]
Fingers return only part of output if the current pane not in full-screen mode. We can see here clearly, what some part of fingers output, located in copy mode, above the screen.
![gif](https://habrastorage.org/webt/z8/ck/6t/z8ck6trrjoxfwoc5-xtptpfsro0.gif)

This problem doesn't show up if pane is zoomed or contains in window which has only one pane (not splitted).

---
Tmux 2.6 linux x64

UPD: @Morantron I made a fix, please see https://github.com/Morantron/tmux-fingers/pull/45

**Comment by Morantron** [comment]
Fixed in latest version 💃
