### ISSUE TITLE
Configure which "backend" to use when searching

### ISSUE THREAD

**Issue by mbark** [Morantron/tmux-fingers#46]
I recently installed this and just want to say that this a really amazing plugin! Incredible simple yet clever idea 👍 

### Background
- I want to add a pattern to match semantic versions (the pattern, if you are interested, looks like this: `([0-9]+)\.([0-9]+)\.([0-9]+)(?:(\-[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+[0-9A-Za-z-\-\.]+)?`);
- `grep` doesn't think this is a valid regex;
- [`ripgrep`](https://github.com/BurntSushi/ripgrep) however, handles the regex just fine.

Now I could debug why `grep` doesn't like the regex but in general I prefer to use `ripgrep` over `grep` whenever possible. Which leads me to the question:

What do you think about having the option to configure which "backend" to use:
- either by defining which command to run (default: `grep` but in my case configured to `rg`);
- or a list of backends where the first one available is chosen (i.e. `rg ag grep`, will check if `rg` exists, otherwise fallback to `ag` etc)?

 If you are interested I can see if I can throw a pull request together.

**Comment by Morantron** [comment]
That's a good question!

I'm afraid right now it'd be very difficult to implement switchable regexp backends.

tmux-fingers uses [gawk](https://github.com/morantron/tmux-fingers/blob/master/scripts/hinter.awk) ( beware, shitty script ahead :trollface: ) under the hood to match, render and build a lookup table in a single pass.

This is done for two reasons mainly:

* Performance: just one script doing all the heavy lifting in a single pass is quickier. From previous experience ( see how it was done [in version 0.1.6](https://github.com/morantron/tmux-fingers/blob/6c297dee650fd4abbf554d5ebe9dd3416e411dbb/scripts/hints.sh#L55) ), relying on a bash script has lots of process overhead and poor performance.

* Rendering: `grep` does not provide column info about the match, making it very hard to render tags at the correct position.

So, having a single awk script doing all the stuff makes it very hard to plug in an alternative regexp backend. I suggest you try to debug your regexp with `grep -E`, which is what gawk uses underneath.

Maybe in the future, if I rewrite everything and tmux-fingers stops being a shitty gigantic shell script, alternative regexp backends can be a possibility. Right now I think it's very complicated 💀 

If you think of an alternative approach let me know 🙏

**Comment by mbark** [comment]
Fair enough! I'll just have to debug why `grep -E` doesn't like the regexp then. Thanks for the quick response :)
