### ISSUE TITLE
`tmux last-pane` gives error "No last pane" after tmux-fingers was used

### ISSUE THREAD

**Issue by ght** [Morantron/tmux-fingers#48]
## Observed behavior
Using tmux-fingers breaks `tmux last-pane` (by default `prefix`+`;`). This seems to be caused by the new window it opens, so it might be related to #31.

## Desired behavior
`tmux last-pane` should work after using tmux-fingers. The pane that was last pane before the overlay opens should be restored as last pane after is closed again.

**Comment by ght** [comment]
Nice, just tested the fix, works great!

**Comment by Morantron** [comment]
Ooops, seems this has been reintroduced.

**Comment by Morantron** [comment]
Fixed again in 2.1.4
