### ISSUE TITLE
if there are no matches don't capture user input

### ISSUE THREAD

**Issue by acornejo** [Morantron/tmux-fingers#5]
Sometimes you run tmux fingers on a screen that doesn't have anything that tmux-fingers recognizes a link. However, fingers still requires user input. It would be a better user experience if simply fingers gets out of the way (and maybe display a message on tmux saying no matches were found)

**Comment by Morantron** [comment]
Yep, makes sense!

You can still exit tmux-fingers by pressing `Ctrl-C`, I'll add an Usage section in the readme explaining this.

**Comment by dragon788** [comment]
Would be nice to also accept Esc to exit out of input mode as I remap that to Caps and it only requires a single press. :)

**Comment by Morantron** [comment]
Ctrl-C and ESC work for exiting fingers mode
