### ISSUE TITLE
gitlab merge requests url copy

### ISSUE THREAD

**Issue by albasili** [Morantron/tmux-fingers#51]
When pushing a new branch to a gitlab repo I have a response that goes like this

``` shell
remote:
remote: To create a merge request for regression-updates, visit:
remote:   https://gitlab.melexis.com/msde-bvx/msenv/merge_requests/new?merge_request%5Bsource_branch%5D=regression-updates
remote:
To gitlab.melexis.com:msde-bvx/msenv.git
 * [new branch]        regression-updates -> regression-updates
Branch regression-updates set up to track remote branch regression-updates from origin.
```
So I would like to copy the url, but unfortunately the text is partially copied, oly untile the ``%`` sign.
Is there some settings I can do to take care of this issue?

**Comment by Morantron** [comment]
Weird, it works in my machine :tm: Can you check which tmux-fingers version do you have? You can do so by entering fingers-mode and then pressing <kbd>?</kbd>

Also `.tmux.conf`, OS bash/gawk versions can help identify the issue.

Thanks :dancing_women:

**Comment by albasili** [comment]
Here's the info:
tmux-fingers ( 0.7.2 )
[.tmux.conf](http://sprunge.us/CUPsJo)
OS debian-stable
GNU bash, version 4.4.12(1)-release (x86_64-pc-linux-gnu)
GNU Awk 4.1.4, API: 1.1 (GNU MPFR 3.1.5, GNU MP 6.1.2)

**Comment by Morantron** [comment]
Cannot reproduce
