### ISSUE TITLE
Extra brackets at the end in urls

### ISSUE THREAD

**Issue by mimame** [Morantron/tmux-fingers#52]
First of all thanks for this awesome tmux plugin! Keep it up!

When I hint a markdown document I have a minor issue because of extra brackets at the end in urls

Result
`([mimadrid](https://github.com/mimadrid))[i]`

Expected
`([mimadrid](https://github.com/mimadrid[i]))`

The pattern is https://github.com/Morantron/tmux-fingers/blob/master/scripts/config.sh#L57 but I don't know a proper solution to this also I think that the fault is totally mine by not add spaces to both sides of the url :/

I hope to be useful

Thanks a lot again for your hard work!

**Comment by Morantron** [comment]
this should be matched properly in latest version
