### ISSUE TITLE
Disables the colors in my theme

### ISSUE THREAD

**Issue by peey** [Morantron/tmux-fingers#57]
How it looks like by default:
![image](https://user-images.githubusercontent.com/4688870/47272267-d3d16800-d5a0-11e8-9ddd-2a72093d2813.png)

After activating fingers:
![image](https://user-images.githubusercontent.com/4688870/47272271-dcc23980-d5a0-11e8-98ab-38b897042c31.png)

Is there a way to fix this? I'd prefer if the text which isn't active for selection is just left alone

**Comment by Morantron** [comment]
Hi! I'm afraid that's the way it works, adding support for that would require rewriting the core of the plugin. Sorry :pray:
