### ISSUE TITLE
[Feature request] Move cursor to the position of the hints

### ISSUE THREAD

**Issue by snippins** [Morantron/tmux-fingers#60]
As the title said, it would be nice have the cursor move to the the location of the hint you type.

This is because we can not predict all kind of texts we might want to copy, so this feature would be helpful and speed things up (by moving the cursor to a good starting point) whenever that happen.

Also, if you want to do this, you might want to do both copying and moving the cursor at the same time because:
+ if the text you want to copy happens to match some regex you are done.
+ if it is not, your cursor would be moved to a good starting point.

**Comment by Morantron** [comment]
Hi! Sorry I don't understand your proposal 🙈 There is no concept of cursor in this plugin. Can explain your idea in another way?

Thanks 🙌

**Comment by snippins** [comment]
Hi, sorry if it is confusing. 

I understand there is no concept of cursor in the plugin, I'm proposing an addition behavior after we type a hint. This involves moving the cursor in tmux copy mode after we type a hint.

I am using **@fingers-compact-hints=1** and **@fingers-hint-position**, so the hints are appeared right at the start of the matches in my case.

Assuming we are in copy mode, and call tmux-fingers to copy something. Sometimes the text we want to copy does not match the regexes we defined, but the location of the hints might be a good starting point to start selecting the text.

So the idea is to **move the cursor in copy-mode of tmux to  the location of the typed hint**, basically like the plugins easymotion (for Vim) or acejump (for Emacs).

With this additional behavior, if the text we want to copy match the regexes we define, we are done as usual. If it isn't, as the cursor in copy mode is moved to the location of the hint we just type, we can start to select and copy text manually using normal tmux shortcuts.

For example: if we want to copy "text1 text2", but our regexes only able to match "text1", after typing the hint for "text1", "text1" is copied to clipboard as usual, but now the cursor position is also moved to the start of "[t]ext1" (at the t letter). Now we can start copying "text1 text2" manually (not related to tmux-fingers).

**Comment by Morantron** [comment]
Interesting. The main gotcha that I see, is that duplicate matches have the same hint, so not sure what to do in those cases. Any ideas?

**Comment by snippins** [comment]
I see. 

My solution: 

+ We first put the cursor at the first occurrence. This is because even when duplicate matches happens, most of the time it would not affect what we want to copy anyway.

+ For the case where it does have an effect. Then, we provide an additional shortcut to be invoked in tmux copy mode, this shortcut would create different hints for the occurrences so that we can jump to one of them. 

What do you think of it?

Also, I am interesting in making a PR for this feature. Though I need some direction and to know how you want it to be implemented.

**Comment by Morantron** [comment]
Just realized, there is an oncoming feature that could allow this, with some hackery in `.tmux.conf`. 

https://github.com/Morantron/tmux-fingers/pull/61

The idea is that you could put a command in `@fingers-copy-command` that enters copy mode and searches for the result.

I'll check if it's possible when it's released.

**Comment by Morantron** [comment]
Looks like you cannot perform searches programatically in tmux. I took a look at [tmux-copycat](http://github.com/tmux-plugins/tmux-copycat) and it translates `line:col` information of the matches to cursor key strokes.

Problem is we currently don't have that information, so that could be a first step. It can be inferred from [hinter.awk main loop](https://github.com/Morantron/tmux-fingers/blob/master/scripts/hinter.awk#L139).

Would you be interested in implementing that? :pray:

**Comment by snippins** [comment]
Right now I have something like this in my config to solve the problem. 

`set -g @fingers-copy-command 'xclip -i -sel p -f | xclip -i -sel c && xdotool key ctrl+s key shift+slash key ctrl+shift+v key Return'
`
With "Ctrl+s" as the shortcut used to enter copy mode, don't ask why lol.

**Comment by Morantron** [comment]
hey that's cool! :ok_hand: 

you can set it to `@fingers-copy-command-uppercase` so it only triggers when you hold SHIFT while entering the hint

**Comment by snippins** [comment]
Thanks for the info, also I literally just thought about this and made the command like 1 hour ago :). Should I close this? It would be a good example to put in README.md I think.

Bonus the command to search downward instead

`set -g @fingers-copy-command 'xclip -i -sel p -f | xclip -i -sel c && xdotool key ctrl+s key H key slash key ctrl+shift+v key Return'
`

I use copy-mode-vi so H will make the cursor go to the top of the terminal screen.

**Comment by Morantron** [comment]
You can know bind custom actions in `@fingers-ctrl-action`, `@fingers-shift-action` and `@fingers-alt-action`.
