### ISSUE TITLE
[Bug] tmux-fingers crashing because of heredoc

### ISSUE THREAD

**Issue by rrhuffy** [Morantron/tmux-fingers#63]
Problem:
When using tmux-fingers (either by Prefix+F or by ~/.tmux/plugins/tmux-fingers/scripts/tmux-fingers.sh) I can see for a quarter of a second newly created tmux pane and then it disappears and finally nothing is happening.
OS: Mint 19.1 XFCE, bash version: 4.4.19(1), tmux version: 2.6, tmux-fingers: newest develop.

Bug probably was introduced here:
https://github.com/Morantron/tmux-fingers/commit/a11afa87567ed6d16c74c1bca9dbecbe390b0e46
When I change file ~/.tmux/plugins/tmux-fingers/scripts/fingers.sh like this:
```
-  copy_command_parameters=<<-EOS
-    printf \"$result\" |
-      IS_UPPERCASE=$is_uppercase
-      HINT=$hint
-      CURRENT_PANE_ID=$current_pane_id
-      $exec_prefix
-  EOS
+  copy_command_parameters=printf \"$result\" | IS_UPPERCASE=$is_uppercase HINT=$hint CURRENT_PANE_ID=$current_pane_id $exec_prefix
```
Then everything is working properly. Command line in both options says only "create pane failed: size too small" twice, without any additional info when crashing. More info is probably in that newly created pane, but it is disappearing too quickly to read

**Comment by Morantron** [comment]
Hi! `master` branch should be used. Can you check when you cloned tmux-fingers repo? `ls -lah /path/to/tmux-fingers` should show it. I'll push a fix to `develop` soon.

**Comment by rrhuffy** [comment]
Ok, now I understand why on my old machine (half of a year old one) git is on develop and new one (from today) is set on master ;-)
Both downloaded by tpm. 
(I've used notes from last install [0.5y ago] and I started to investigate why I can't find given string in fingers.sh on new one) 
When I did git checkout master then everything is working, but you should know that develop branch version is failing on some machines ;-)

**Comment by Morantron** [comment]
fixed now! :raised_hands:
