### ISSUE TITLE
[Feature request] Make several copies and pastes for very link

### ISSUE THREAD

**Issue by vnikk** [Morantron/tmux-fingers#66]
It would be nice to be able to stay enter copy mode and start copy-pasting the selected links without leaving copy mode. Continuation of #50

**Comment by vnikk** [comment]
#50

**Comment by Morantron** [comment]
Available in 1.0.0. You can hit <kbd>TAB</kbd> select some matches, and then hit <kbd>TAB</kbd> again.

**Comment by vnikk** [comment]
> Available in 1.0.0. You can hit TAB select some matches, and then hit TAB again.

Man! this is insanely beautiful! thanks so much
