### ISSUE TITLE
Inconsistent failure to copy

### ISSUE THREAD

**Issue by theryangeary** [Morantron/tmux-fingers#69]
When trying to copy something, tmux-fingers will sometimes work, but sometimes fail, giving this message:

```
printf "2147483648" | nohup bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel wl-copy' returned 127
```
I'm trying to figure out what's going on here and could use some help.
I'm using tmux-fingers with tag 0.10.1 (hash 8432c1a), tmux 2.9a, swaywm, and wl-clipboard on arch.

**Comment by Morantron** [comment]
should be fixed in 1.0.0
