### ISSUE TITLE
Ctrl + a-z fails to open a link on Ubuntu when the kbd package is installed

### ISSUE THREAD

**Issue by lacygoill** [Morantron/tmux-fingers#70]
**Describe the bug**

When pressing a hint which targets a url while pressing the Ctrl modifier key, the url is not opened in the browser if the [`kbd`](https://packages.ubuntu.com/eoan/kbd) package is installed; the latter installs a symlink at `/bin/open` which points to `/bin/openvt`.

**To Reproduce**

Install the `kbd` package:

    $ sudo apt-get install kbd

Clone the plugin in a directory:

    $ git clone https://github.com/Morantron/tmux-fingers

Initialize the submodules:

    $ git submodule update --init --recursive

Write this in `/tmp/tmux.conf`:

    run /run/user/1000/tmp/tmux-fingers/tmux-fingers.tmux

Start Tmux with this minimal config file:

    $ tmux -Lx -f/tmp/tmux.conf

Run this shell command:

    $ echo 'https://github.com/Morantron/tmux-fingers'

Press `C-b` and `F` to generate a hint; then press `Ctrl` plus the hint which targets the url.

The url is not opened, and this error message is displayed:

    'printf "https://github.com/Morantron/tmux-fingers" | MODIFIER=ctrl HINT=s  xargs open' returned 123

**Expected behavior**

The url is opened in the web browser, and no error message is displayed.

**Environment**

 - plugin version: commit 0ce16f5685fa5bece4c6c60353d1948f693f6701
 - Tmux version: `tmux next-3.1`
 - OS: Ubuntu 16.04.6 LTS
 - Terminal: XTerm(322)

**Additional context**

I think the issue comes from these lines:
https://github.com/Morantron/tmux-fingers/blob/0ce16f5685fa5bece4c6c60353d1948f693f6701/scripts/config.sh#L76-L79

Right now, I've reversed the order of the 2 `if`/`elseif` clauses:

    if [[ $(program_exists "xdg-open") = "1" ]]; then
      echo "xargs xdg-open"
    elif [[ $(program_exists "open") = "1" ]]; then
      echo "xargs open"

Which fixes my issue. I don't know whether it would cause an issue on other OSes.
I would naively think it's ok, because `xdg-open` is more specific than `open`, so it makes sense to test it first, but I could be wrong.

**Comment by Morantron** [comment]
thanks for the detailed explanation :muscle: should be fixed in 1.0.1, you'll probably need to resource your tmux.conf after updating the plugin

**Comment by dufferzafar** [comment]
I'm still facing this issue!

**Comment by Morantron** [comment]
Are you on **tmux-fingers@1.0.1**? You can out by entering fingers mode and pressing <kbd>?</kbd>

If you are, open a shell within tmux and try

```
echo $FINGERS_SYSTEM_OPEN_COMMAND
```

This should output the command which is being used to open files. If it's empty it probably means that you need to resource your tmux.conf after updating the plugin

**Comment by dufferzafar** [comment]
@Morantron Yes, I'm on 1.0.1

I changed the config.sh script by copying the command from tmux-open:

```bash
elif [[ $(program_exists "xdg-open") = "1" ]]; then
  echo "xargs -I {} tmux run-shell -b 'cd #{pane_current_path}; xdg-open \"{}\" > /dev/null'"
```

This worked for me!

**Comment by dufferzafar** [comment]
BTW, yes, `echo $FINGERS_SYSTEM_OPEN_COMMAND` was empty!

**Comment by Morantron** [comment]
Run `tmux source ~/.tmux.conf` and it should work :tm: without editing config.sh
