### ISSUE TITLE
Broken on macOS Mojave 10.14.6

### ISSUE THREAD

**Issue by pedromss** [Morantron/tmux-fingers#71]
### System description
- macOS: Mojave 10.14.6
- zsh: 5.3
- tmux: 2.9a
- iterm2: 3.3.7

Also tested on the macOS terminal app 2.9.5

### Problem
After pressing `prefix + F` (capital F, means `shift + f`):
- All text becomes white
- A new tmux pane is opened with `fingers` in the name but focus is kept on the original window
- Nothing happens pressing any shortcuts in the docs
- After pressing ESC, no tmux commands work at all

**Comment by Morantron** [comment]
Hi! Can you run`/path/to/tmux-fingers/scripts/health-check.sh` and post the output here ( if any )?

**Comment by pedromss** [comment]
Hey @Morantron sure:

```
17:09:51 ❯ scripts/health-check.sh                                                                                  0
+------------------------------------------------------------------------------+
| tmux-fingers health-check:                                                   |
|                                                                              |
|   * bash version "3.2.57(1)-release" is too old. bash 4.x+ is required.      |
|                                                                              |
| Follow this link for help on fixing issues:                                  |
|                                                                              |
|   https://github.com/Morantron/tmux-fingers/blob/master/docs/health-check.md |
|                                                                              |
+------------------------------------------------------------------------------+
```

The thing I'm using zsh:

```
17:09:58 ❯ echo $SHELL                                                                                              
/bin/zsh
```

**Comment by pedromss** [comment]
Brew tells me I already had 5.0.2 installed.
```
17:12:16 ❯ brew upgrade bash                                                                                        
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/cask-versions and homebrew/cask).
No changes to formulae.

==> Upgrading 1 outdated package:
bash 5.0.2 -> 5.0.11
==> Upgrading bash
...
```

But when I run `bash` I get version 3.2. I probably have both installed and it is picking up the 3.2?

Should this be a problem when running ZSH instead of bash?

**Comment by Morantron** [comment]
`/usr/bin/env bash --version` tells you which bash version tmux-fingers is using.

From what I see in [here](https://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx) you might need to add `/usr/local/bin/bash` to `/etc/shells`

**Comment by pedromss** [comment]
Yup. Using the 3.2 apparently. Already added it to `/etc/shells` but it still uses `/bin/bash` even tho I removed it from `/etc/shells`.

I can't rename `/bin/bash` (permission stuff)

**Comment by Morantron** [comment]
Oops, looks like the `/etc/shells` thing is of no use.

Apparently what you need to do is to have `/usr/local/bin` in your PATH environment variable, *before* `/bin`.

**Comment by pedromss** [comment]
Solved ;) Thanks!

**Comment by Morantron** [comment]
:raised_hands:

**Comment by jason0x43** [comment]
I'm seeing this same issue, or something very similar, on Catalina.

* macOS 10.15.2
* tmux 3.0a
* zsh 5.7.1
* bash 5.0.11

As in the original issue, hitting `<prefix>+F` turns all the text white and opens a new pane named "fingers".

Pressing a letter or number key doesn't appear to do anything. If I press escape afterwards, the normal terminal colors return, but my tmux prefix no longer works; pressing it just prints a control character at the prompt. I can restore my key bindings with `tmux source ~/.tmux.conf`.

If I press `<prefix>+F`, and then immediately hit escape, the pane I'm in clears and displays the following text at the top:

```
'printf "C-s" | MODIFIER=C-s HINT=C-s  -S_ACTION' return 127
```

Pressing any key at that point restores the original terminal contents, and my normal keybindings work.

I ran the health check script, and it didn't output anything.

**Comment by Morantron** [comment]
> I'm seeing this same issue, or something very similar, on Catalina.
> 
>     * macOS 10.15.2
> 
>     * tmux 3.0a
> 
>     * zsh 5.7.1
> 
>     * bash 5.0.11
> 
> 
> As in the original issue, hitting `<prefix>+F` turns all the text white and opens a new pane named "fingers".
> 
> Pressing a letter or number key doesn't appear to do anything. If I press escape afterwards, the normal terminal colors return, but my tmux prefix no longer works; pressing it just prints a control character at the prompt. I can restore my key bindings with `tmux source ~/.tmux.conf`.
> 
> If I press `<prefix>+F`, and then immediately hit escape, the pane I'm in clears and displays the following text at the top:
> 
> ```
> 'printf "C-s" | MODIFIER=C-s HINT=C-s  -S_ACTION' return 127
> ```
> 
> Pressing any key at that point restores the original terminal contents, and my normal keybindings work.
> 
> I ran the health check script, and it didn't output anything.

weeeiiird :scream_cat: can you share a screen recording?

**Comment by jason0x43** [comment]
Hmmm...apparently that was a false alarm. After restarting my terminal and tmux, tmux-fingers is working properly now. ¯\_(ツ)_/¯

**Comment by Morantron** [comment]
![](https://media.giphy.com/media/kH6EFgDSbnkZsmedbK/giphy.gif)

**Comment by jason0x43** [comment]
lol, I just started watching Schitt's Creek and thought that looked familiar... 😄

**Comment by kdheepak** [comment]
I am having the same issue as the original poster on MacOS. This is my system information:

![73869360-5e29f380-4807-11ea-9658-49781b573f9d](https://user-images.githubusercontent.com/1813121/73869572-c547a800-4807-11ea-8f0e-0050c1459b32.png)

This is my .tmux.conf file:

https://github.com/kdheepak/dotfiles/blob/7f9b315eed442973db5b99c93df933789c7a5e92/.tmux.conf

This is a gif of the screenrecording of the issue:

![Screen Recording 2020-02-05 at 10 30 10 AM](https://user-images.githubusercontent.com/1813121/73869653-f1fbbf80-4807-11ea-9702-16506bf87d37.gif)

It's a little fast. So I'll describe what is going on:

1) I hit enter which runs `ls`
2) I hit ``` ` + Shift + f```, since ``` ` ``` is my tmux prefix
3) All colors are removed from the current terminal and we enter fingers mode 
4) Some parts of the terminal are highlighted with a prefix letter
5) I hit `g`, one of the highlighted prefix and it copies `~/g/dotfiles` and paste it into the REPL, and then backspace the contents on the current line.

Any suggestions on what might be going on?

**Comment by Morantron** [comment]
Yep. That's the expected behavior.

* Colors are removed in fingers mode
* Relative paths are usually not matched ( try another command like `git log` and you'll see more matches )

This might change in a future version, but I can assure you it will take long to be released :joy:

**Comment by staranto** [comment]
Same problem as @jason0x43 above.

macOS 11.0.1 (Big Sur)
tmux 3.1c
SHELL=/bin/zsh   # (5.8)
which bash   # /usr/local/bin/bash
env bash  --version  # 5.1.4(1)-release
 
- Start tmux and do a git log to give tmux-fingers something to work with.
- C-Q Z (which is my tmux-fingers binding).
- fingers matches and key letters are highlighted, but....
- Goes into tmux rename-window mode.

Did all the usual restarting of tmux, shell, iTerm2, etc.  No dice.
