### ISSUE TITLE
SHA hash value length

### ISSUE THREAD

**Issue by IngoHeimbach** [Morantron/tmux-fingers#73]
Hey, thanks for the nice project.
Is there a specific reason to limit SHA hashes to 40 characters? I know that Git uses 160 bit SHA hashes but some applications use SHA-256 or even 512. In this case `tmux-fingers` truncates hashes to 40 characters.

**Comment by Morantron** [comment]
No particular reason, what length in chars should be added?

**Comment by IngoHeimbach** [comment]
Hmm, I think that SHA-512 currently produces the longest hash values (128 hexadecimal digits in total).

**Comment by Morantron** [comment]
Cool! Added in 1.1.0

**Comment by IngoHeimbach** [comment]
Thanks! :+1:
