### ISSUE TITLE
How to use fingers with previous pane

### ISSUE THREAD

**Issue by sabrehagen** [Morantron/tmux-fingers#77]
Often I scroll back through pages of terminal output looking for a string. Once I reach the page containing the desired string, how can I activate tmux-fingers on the pane contents? Tmux is in the mode where it shows `[6/34]` or something similar in the top right hand corner, and when I try Prefix + F it jumps to the bottom of the scrollback.

**Comment by Morantron** [comment]
I think you are referring to copy mode. What version of tmux are you using? It should work on 2.2 or newer, although I recommend using a more recent version that that
