### ISSUE TITLE
hints could be shorter for many equal matches

### ISSUE THREAD

**Issue by IngoMeyer441** [Morantron/tmux-fingers#80]
Hey and thanks for tmux-fingers, it is a great tool and it helped me a lot to learn about tmux plugin programming!

I noticed a minor issue when many equal matches are present:

![image](https://user-images.githubusercontent.com/1449087/104468765-1c2d3400-55b8-11eb-9396-23fc4407c6d2.png)

The count of needed key presses seems to determined before the filtering of unique matches. If it would be applied before, one key stroke could be saved in this case. This happens quite often for me because my hostname in my zsh prompt is always matched in fingers mode.

**Comment by Morantron** [comment]
Hey! That's true. It's already taken care of in the upcoming 2.0.0 version, but won't be fixed in 1.x.x.

You can track progress here https://github.com/Morantron/tmux-fingers/pull/79 It's almost there :tm: :joy:

**Comment by IngoMeyer441** [comment]
Ah great, I will definitely check out the new version. 😄 👍
