### ISSUE TITLE
tmux-fingers nix(os) package? 

### ISSUE THREAD

**Issue by kidd** [Morantron/tmux-fingers#81]
NixOS provides tmux-fingers package, but I couldn't get it working. Anyone succeeded there?

tmux-fingers needs to write a .cache file, and nix doesn't allow it due to the RO store.

**Comment by kidd** [comment]
Ok, I really can't understand how it works (no idea where the .cache directory ends up being created), but if you have tmuxPlugins.fingers in your systemPackages: 

```
  programs.tmux= {
    enable = true;
    extraTmuxConf= ''
      run-shell ${pkgs.tmuxPlugins.fingers}/share/tmux-plugins/fingers/tmux-fingers.tmux
    '';
  };
```
It Just Works :tm:

**Comment by Morantron** [comment]
woooaah, sorry I have 0 idea about nixos, didn't even know there was a tmux-fingers package :joy:

thanks for the workaround!
