### ISSUE TITLE
tmux-fingers window does not show matches in tmux 3.1c

### ISSUE THREAD

**Issue by jmcphers** [Morantron/tmux-fingers#82]
I'm using tmux-fingers with a relatively new version of tmux (3.1c). When I invoke `prefix`+`F`, I get a `[fingers]` window, but all of the stuff that should be copyable is blanked out.

Example, before invoking tmux-fingers:

![image](https://user-images.githubusercontent.com/470418/116760091-e4ac9100-a9c8-11eb-93a7-6f02db15b6fc.png)

After invoking tmux-fingers:

![image](https://user-images.githubusercontent.com/470418/116760111-f2faad00-a9c8-11eb-8f2f-f2e760950f93.png)

The health-check and hints scripts don't return anything.

![image](https://user-images.githubusercontent.com/470418/116760184-1faec480-a9c9-11eb-9198-70b6e25fab45.png)

Is tmux-fingers compatible with tmux 3?

**Comment by jmcphers** [comment]
Seems to be fixed by upgrading from 3.1c -> 3.2.

**Comment by Morantron** [comment]
usually this is fixed by resourcing your `tmux.conf`
