### ISSUE TITLE
How to copy text from another pane?

### ISSUE THREAD

**Issue by bimlas** [Morantron/tmux-fingers#83]
I want to copy text from the other pane, which can be done by these steps but it's a bit cumbersome: I switch to the other pane -> copy the text -> switch back to the original pane -> paste the text.

Is there a way for me to copy the text from any pane?

**Comment by Morantron** [comment]
It is not possible right now, but is something that I want to add (or make possible to do) in the [upcoming 2.0 release](https://github.com/Morantron/tmux-fingers/pull/79)
