### ISSUE TITLE
nounderscore not removing underline

### ISSUE THREAD

**Issue by novasenco** [Morantron/tmux-fingers#84]
for example `set -g @fingers-highlight-format-nocompact "#[fg=blue,bold](#[fg=colour9,nobold,underscore]%s#[fg=blue,bold,nounderscore])"`

The close parenthesis is still underlined.

**Comment by novasenco** [comment]
Also, "fg=brightred" seems to break. I had to use "fg=colour9" instead

**Comment by Morantron** [comment]
You can move `nounderscore` to the beginning of the style and it will work

    set -g @fingers-highlight-format-nocompact "#[fg=blue,bold](#[fg=colour9,nobold,underscore]%s#[nounderscore,fg=blue,bold])"

I'll add tests for the upcoming 2.0 release for theses cases in https://github.com/Morantron/tmux-fingers/pull/79
