### ISSUE TITLE
:open: dosen't work

### ISSUE THREAD

**Issue by yueyihui** [Morantron/tmux-fingers#85]
when i do fingers-ctrl-action, it print erros as below:

'printf "src/IMDB/src/db_module.cpp" | MODIFIER=ctrl HINT=f  xargs xdg-open' returned 123

tmux version: tmux next-3.3
bash version: GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)
gawk version: GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)

**Comment by yueyihui** [comment]
I tried, below code works

tmux run-shell -b "printf \"$(escape_quotes "${state[final_result]}")\" | xargs -I {} tmux send-keys 'vim -- {}'; tmux send-keys 'C-m'"

**Comment by atomsfat** [comment]
On OSX Tmux 3.2.a and fingers version eba6ee2d553ac9783428c4ca99114be4523fc9c8 

` 'printf "eba6ee2d553ac9783428c4ca99114be4523fc9c8" | MODIFIER=shift HINT=jo  xargs bat' returned 1`

**Comment by atomsfat** [comment]
> On OSX Tmux 3.2.a and fingers version [eba6ee2](https://github.com/Morantron/tmux-fingers/commit/eba6ee2d553ac9783428c4ca99114be4523fc9c8)
> 
> ` 'printf "receiver.json" | MODIFIER=shift HINT=jo xargs bat' returned 1`

Mi bad it is working as expected

**Comment by atomsfat** [comment]
I'm having the same problem, the problem is related with relative and absolute path if it is absolute it works and if it is relative if will fail
