### ISSUE TITLE
`gawk` allocates all system memory when searching for pattern that matches empty string

### ISSUE THREAD

**Issue by psacawa** [Morantron/tmux-fingers#86]
With a simple test configuration like this: 

```
set -g @fingers-pattern-0 '(token)?'
``` 

the plugin's gawk subprocess allocates all system ram and swap, locking the machine, and eventually gets killed by OOM killer. This happens while executing `scripts/hinter.awk` script.

GNU Awk 5.0.1, most recent tmux and plugin versions

**Comment by psacawa** [comment]
Adding

```
if (RLENGTH == 0) {
  break;
}
```

at [https://github.com/Morantron/tmux-fingers/blob/eba6ee2d553ac9783428c4ca99114be4523fc9c8/scripts/hinter.awk#L63](in the while loop) confirms that this loop is going indefinitely, allocating memory indefinitely.

**Comment by fcsonline** [comment]
I'm facing the same issue.

**Comment by Morantron** [comment]
fixed in https://github.com/Morantron/tmux-fingers/pull/87

**Comment by fcsonline** [comment]
Awesome!
