### ISSUE TITLE
xdg-open is not working as expected

### ISSUE THREAD

**Issue by lrustand** [Morantron/tmux-fingers#91]
When using tmux-fingers to open files it does not open the correct application. I have setup xdg-open to open vim for plaintext files and this works correctly when I run `xdg-open somefile.txt`, but when I try to open the same file from tmux-fingers it opens in the browser. I see that the actual command executed by tmux-fingers is `printf "somefile.txt" | MODIFIER=ctrl HINT=v  xargs xdg-open`. This command also does what it is supposed to when I run it on the command line manually, but apparently not when tmux-fingers runs it.

**Comment by Morantron** [comment]
can you try in latest version? 🤔
