### ISSUE TITLE
Problem with long lines

### ISSUE THREAD

**Issue by perpen** [Morantron/tmux-fingers#92]
Apologies if this has been answered before, I couldn't find a related issue.

When I have long wrapping lines, triggering fingers shifts the screen up.
Eg if the pane has 2 lines and 4 columns wide and I have a line of length 4:
```
1234
....
```
Then all is good.

But if a line wraps:
```
1234
56..
```
then triggering fingers hides the first line and gives me:
```
56..
....
````
This shift-up gets worse as I have more long lines.

**Comment by Morantron** [comment]
should be fixed in latest version
