### ISSUE TITLE
Space not working to switch from compact mode

### ISSUE THREAD

**Issue by mkowske** [Morantron/tmux-fingers#94]
I can enter into fingers mode fine (compact displayed by default), but then hitting space to switch to regular view does nothing. This was working before I updated to the latest version. There is no error displayed that I can see.

Possibly related, Ctrl+hint does not seem to work either (seems to have no effect). Shift+hint does work to paste immediately.

**Comment by Morantron** [comment]
compact mode switching has been deprecated
